### ISSUE TITLE
Keep the changelog up to date

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#139]
I noticed that I opened several PR without updating the changelog. For instance #61 #90. I was thinking to open a PR where I update the changelog and I also add this simple action to remind the author of the PR to update the changelog https://github.com/marketplace/actions/changelog-checker  

As far as I understood the setting `noChangelogLabel` can be used to avoid running the CI.

@traversaro @S-Dafarra @prashanthr05 do you have any suggestion?

**Comment by GiulioRomualdi** [comment]
Also this one could be a valid option: https://github.com/marketplace/actions/missing-changelog-reminder

**Comment by prashanthr05** [comment]
Thanks! That'd be helpful. I was also wondering about this.

**Comment by prashanthr05** [comment]
YARP uses something like this https://github.com/apps/update-docs. I am not sure if it would be relevant.

**Comment by GiulioRomualdi** [comment]
In #140 I used https://github.com/marketplace/actions/changelog-checker but also https://github.com/apps/update-docs is really nice. I'm open to discussion :smiley:
