### ISSUE TITLE
Migrate Contact library outside Planners folder

### ISSUE THREAD

**Issue by prashanthr05** [dic-iit/bipedal-locomotion-framework#162]
In https://github.com/dic-iit/bipedal-locomotion-framework/pull/142, we identified the `Contact` class to have a more generic usage extending beyond just planning. 
So we abstracted the current Contact class into a `ContactBase` class and implemented derived classes `PlannedContact` and `EstimatedContact` classes.

In order to not break the current workflows and python bindings related merges, I created a new library `Contacts` and added only the above mentioned classes (See https://github.com/dic-iit/bipedal-locomotion-framework/pull/142#discussion_r522830098). 
However, it would make sense to eventually move other contacts-related components from the `Contact` library that are currently existing in the `Planners` folder as well into the new `Contacts` folder.

Consequently, we might also have to make changes in the python bindings generation? (do we? please correct me if I am wrong.)
Specifically, the changes will be
- renaming of `Contact` as `PlannedContact`
- renaming `ContactList`, `ContactPhase`, `ContactPhaseList` to corresponding `PlannedContact` equivalents
- replacing using namespace Planners` to `using namespace `Contacts`

cc @GiulioRomualdi @S-Dafarra  @diegoferigo

**Comment by diegoferigo** [comment]
No problem for the renaming from my side, I don't have much code to migrate and I think I'm the only one that developed in the past weeks some code in Python.

> Consequently, we might also have to make changes in the python bindings generation? (do we? please correct me if I am wrong.)

Yes there are few required changes, for instance (they might not be all of them):

- [`bindings/python/Contacts.cpp`](https://github.com/dic-iit/bipedal-locomotion-framework/blob/f58eb5863e6a685d4805a8b193c7871d1b3ac1a2/bindings/python/Contacts.cpp)
- [`python/tests/test_contact.py`](https://github.com/dic-iit/bipedal-locomotion-framework/blob/f58eb5863e/bindings/python/tests/test_contact.py)
- [`python/tests/test_time_verying_dcm_planner.py`](https://github.com/dic-iit/bipedal-locomotion-framework/blob/f58eb5863e/bindings/python/tests/test_time_verying_dcm_planner.py)

**Comment by prashanthr05** [comment]
Thanks @diegoferigo. I will open a PR after https://github.com/dic-iit/bipedal-locomotion-framework/pull/142/files gets merged, and add you as one of the reviewers for the python part.

**Comment by prashanthr05** [comment]
https://github.com/dic-iit/bipedal-locomotion-framework/pull/142 has been merged. I will proceed with the complete migration soon.
