### ISSUE TITLE
Add initialize function ti advanceable class  

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#196]
I noticed that all the classes that inherit from advanceable have 
```cpp
bool initialize(std::shared_ptr<ParametersHandler::IParametersHandler> handler);
```

we may think to add this function also in the base class.

What do you think @S-Dafarra ??

**Comment by S-Dafarra** [comment]
Yes, sounds good. I did not add it at the beginning because I was not sure yet if that was needed. If it is the case, I think it is a good move. I would simply avoid having it abstract. You can just provide a base implementation returning ``true`` all the times.

**Comment by GiulioRomualdi** [comment]
Yes I agree

**Comment by GiulioRomualdi** [comment]
The only problem is

https://github.com/dic-iit/bipedal-locomotion-framework/blob/bcb8ce2074ebc864a972c2d9133a8f45abb236e6/src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h#L155

It wants as input also the model. I don't know if we can create another method to set the model only. @prashanthr05

**Comment by S-Dafarra** [comment]
> The only problem is
> 
> https://github.com/dic-iit/bipedal-locomotion-framework/blob/bcb8ce2074ebc864a972c2d9133a8f45abb236e6/src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h#L155
> 
> It wants as input also the model. I don't know if we can create another method to set the model only. @prashanthr05

I don't think it is an issue, the implementation of the method you are proposing in ``FloatingBaseEstimator`` will simply return ``false`` as also the model needs to be set. The two versions can leave together thanks to overloading.

**Comment by GiulioRomualdi** [comment]
Ok but in `FloatingBaseEstimation` there is also the following protected method

https://github.com/dic-iit/bipedal-locomotion-framework/blob/bcb8ce2074ebc864a972c2d9133a8f45abb236e6/src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h#L235

**Comment by prashanthr05** [comment]
> Ok but in `FloatingBaseEstimation` there is also the following protected method
> 
> https://github.com/dic-iit/bipedal-locomotion-framework/blob/bcb8ce2074ebc864a972c2d9133a8f45abb236e6/src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h#L235

We can make it public. Indeed, I make it public in the future rolling versions so that we can use the estimator independent from the Model/KinDynComputations for scenarios of visual-inertial odometry. So the user can choose to use the corresponding function call when using a relevant estimator.
