### ISSUE TITLE
Things to do in v0.1.0

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#197]
- [x] Adjust the readme #148 

@S-Dafarra @traversaro @prashanthr05 @isorrentino

**Comment by diegoferigo** [comment]
Are we going to follow [SemVer](https://semver.org/) to cycle the releases or do we wait a bit longer to let the APIs become more mature?

**Comment by GiulioRomualdi** [comment]
> Are we going to follow SemVer to cycle the releases or do we wait a bit longer to let the APIs become more mature?

In theory yes, we can use `SemVer`. However, this shouldn't block us from the development of the library. At this point, we can easily break the API but we have to remember to change the version accordingly.

**Comment by GiulioRomualdi** [comment]
By the way, at this point, we may release `0.1.0` (Check [here](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)

**Comment by diegoferigo** [comment]
Cool, I was not aware that in SemVer the releases 0.x are not API stable.

**Comment by GiulioRomualdi** [comment]
`blf` v0.1.0 has been released today https://github.com/dic-iit/bipedal-locomotion-framework/releases/tag/v0.1.0
