### ISSUE TITLE
Use Constants::gravity instead of hardcoding 9.81

### ISSUE THREAD

**Issue by traversaro** [dic-iit/bipedal-locomotion-framework#210]
See https://github.com/dic-iit/bipedal-locomotion-framework/search?q=9.81 . In many cases, it could also make sense to also expose gravity as an optional parameter to the user. 

See discussion in https://github.com/dic-iit/bipedal-locomotion-framework/pull/208#discussion_r582227016 .

**Comment by prashanthr05** [comment]
Just adding the search results for `9.80665`,  in case we want to modify these as optional parameters and choose to revert to a default parameter if not available.

https://github.com/dic-iit/bipedal-locomotion-framework/search?q=9.80665

**Comment by GiulioRomualdi** [comment]
https://github.com/dic-iit/bipedal-locomotion-framework/search?q=9.81
