### ISSUE TITLE
Create variableHandler from configuration file automatically

### ISSUE THREAD

**Issue by isorrentino** [dic-iit/bipedal-locomotion-framework#286]
It would be nice to have the possibility to create the variableHandler object by loading parameters specified in a configuration file, instead of reading each parameter per time and initializing it by hand.

cc @GiulioRomualdi @S-Dafarra

**Comment by S-Dafarra** [comment]
I am not sure I understood. Can you give an example of expected behavior?

**Comment by GiulioRomualdi** [comment]
I think @isorrentino was referring to adding an initialize method that takes a parameter handler and adds all the variables
