### ISSUE TITLE
Discuss the possibility to drop doygen and move to m.css

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#299]
In these last days, I played a bit with [m.css](https://mcss.mosra.cz/) and I was able to obtain some nice (in my opinion) website containing the documentation. 

Here some examples:
- https://robotology.github.io/osqp-eigen/
-  https://giulioromualdi.github.io/scs-eigen/

Do you have any opinion on moving from doxygen website to m.css? 

cc @S-Dafarra @prashanthr05 @traversaro

**Comment by traversaro** [comment]
I wanted to share this moment with @jeljaik .

**Comment by GiulioRomualdi** [comment]
Here some examples

This is the readme. (Probably we should remove the image and handle the badges in a different way) 
![image](https://user-images.githubusercontent.com/16744101/117431564-add6fd80-af29-11eb-9eef-8c98765b555e.png)

This is an example of the class documentation
![image](https://user-images.githubusercontent.com/16744101/117431746-df4fc900-af29-11eb-9c32-bc1f65414e83.png)

This is the search engine 
![image](https://user-images.githubusercontent.com/16744101/117431855-fee6f180-af29-11eb-8a9b-528bdd47530f.png)

**Comment by S-Dafarra** [comment]
:heart_eyes:

**Comment by DanielePucci** [comment]
This is cool guys, well done

**Comment by jeljaik** [comment]
I have to say that I agree on the decision... but I may be biased 😄
