### ISSUE TITLE
Implement a class that reads the planned footsteps from file

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#315]
Discussing with @paolo-viceconte we realized that it would be nice to have a method/class that reads from a file the position and timings of the footsteps. A possible solution is to use a JSON file (already used by @paolo-viceconte in python)

Here a library that can be used to parse a JSON file https://github.com/nlohmann/json

The library can be installed from apt/vcpkg/brew/conda

cc @traversaro @S-Dafarra

**Comment by traversaro** [comment]
nlohmann/json is a great library, we already use it in yarp-telemetry, fully blessed dep!
