### ISSUE TITLE
Modify the `calibration-delta-updater` to consider hard limits 

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#358]
The[`calibration-delta-updater` ](https://github.com/dic-iit/bipedal-locomotion-framework/tree/master/utilities/calibration-delta-updater) is a really useful tool to speed up the calibration procedure.

The application is based on the assumption that the robot has to be manually moved in the zero configuration. Discussing with @pattacini and @S-Dafarra., we realized that a possible solution is to use the hard limits on the robot. 

Considering that we can modify the  `calibration-delta-updater` to move the robot towards the hardware limit, automatically compute the offset and finally automatically update the configuration file. To reach the hardware limit we can use the PWM interface (already supported in blf #346) and then we can use the `ISensorBridge` to read the joint encoder. 

cc @traversaro @isorrentino @DanielePucci

**Comment by GiulioRomualdi** [comment]
cc @dic-iit/blf-developers

**Comment by S-Dafarra** [comment]
Rather than considering it a special case, a possibility could be to set the individual "expected" values. Those could be all zeros, or the expected encoder measurements when at the limits

**Comment by GiulioRomualdi** [comment]
> Rather than considering it a special case, a possibility could be to set the individual "expected" values. Those could be all zeros, or the expected encoder measurements when at the limits. I would avoid having an automated way to reach those limits. I think it is safer if a person reaches that configuration by hand.

In that case is super trivial to implement

**Comment by S-Dafarra** [comment]
Using the open loop control may make sense for a subset of joints though, like the ankles or the knee. In any case, I think it is not trivial to understand when a joint has actually hit the limit, or instead it is blocked by gravity for example. Also, I am not sure about how to define the signed value of PWM to apply 🤔

**Comment by GiulioRomualdi** [comment]
In #361 I implemented what you suggested in https://github.com/dic-iit/bipedal-locomotion-framework/issues/358#issuecomment-875637690
