### ISSUE TITLE
Implement the simplified model control component

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#384]
In a three-layer controller architecture, the simplified model control layer is in charge to generate a cartesian task trajectory (i.e. the CoM trajectory) considering a simplified model, e.g. LIPM.

In the first implementation of the walking, we implemented the so-called [ZMP-CoM controller.](https://ieeexplore.ieee.org/abstract/document/1642102) 
Since this controller is quite useful we can think to port it also here

----

**Disclaimer:** we all (@S-Dafarra and @DanielePucci)  agree that we should substitute the controller with something better but I was not able to find anything

**Comment by DanielePucci** [comment]
> Disclaimer we all (@S-Dafarra and @DanielePucci) agree that we should substitute the controller with something better but I was not able to find anything

We do :-) We also agree I believe that since the ZMP-CoM controller works, if indeed useful to have it implemented
