### ISSUE TITLE
Improve the naming of the components 

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#47]
I noticed that the libraries created by this repo have a name that is too generic (i.e. `libSystem.so`)
I would suggest adding a suffix to the library name. i.e. `libBipedalLocomotionFrameworkSystem.so`

This can be easily done by adding in the [`AddBipedalLocomotionLibrary.cmake`](https://github.com/dic-iit/bipedal-locomotion-framework/blob/master/cmake/AddBipedalLocomotionLibrary.cmake)
```cmake
set_target_properties(${LIBRARY_TARGET_NAME} PROPERTIES OUTPUT_NAME "${PROJECT_NAME}${LIBRARY_TARGET_NAME}")
```

@traversaro @S-Dafarra

**Comment by S-Dafarra** [comment]
Go!
