### ISSUE TITLE
Bug in ContactPhaseList::cbegin() function

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#59]
There is a copy-paste bug in `ContactPhaseList::const_iterator ContactPhaseList::cbegin() const` function
https://github.com/dic-iit/bipedal-locomotion-framework/blob/557c7c7c9ba1ab71b0daff6ac7120fec1bae9077/src/Planners/src/ContactPhaseList.cpp#L121-L124

**Comment by S-Dafarra** [comment]
Dammit :sweat_smile:
