### ISSUE TITLE
Enable the compilation in Debug for the CI

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-framework#91]
Starting from #63 we started to use `Eigen` actively on the framework. As you probably know `Eigen` suppresses several checks if the consumer library/application is compiled in `Release`, this may lead to undesired behavior that are not easy to spot. See for instance https://github.com/dic-iit/bipedal-locomotion-framework/pull/85#issuecomment-686605967.

Enabling the Debug tag on CI may help the developer to spot some problems. On the other hand, it will increase the compilation time on the GitHub action.

What do you think @S-Dafarra @prashanthr05 @traversaro?

**Comment by S-Dafarra** [comment]
I like the sound of that.
